controller_manager:
  ros__parameters:
    update_rate: 50

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

joint_group_position_controller:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints:
      - joint1
    command_interfaces:
      - position
controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_group_position_controller:
      type: position_controllers/JointGroupPositionController
      joints:
        - joint1
      command_interfaces:
        - position
